### ISSUE TITLE
Enrichment plot seems different

### ISSUE THREAD

**Issue by SaeidehTD** [RitchieLab/eQTpLot#14] opened 2022-03-31 16:43 UTC
Hi, I have been using your awesome code for my GWAS and eQTL analysis. While it generated a beautiful plot. I see that the enrichment graph in your paper marks eQTL enrichment as yellow. However, in my plot, it marks eQTL purple which doe snot match with the story as most of my GWAS significant variants are also eQTL positive as I can see in graph A (similar to your data).I am not sure if this is a labeling bug and how can I fix it? Thanks for your help, Saeideh

**Comment by TGDrivas** [comment] 2022-03-31 16:50
Hi Saeideh, glad you are enjoying our package! Would you be able to post a photo of the resulting plot so I can make sure I understand the issue? -Teddy

**Comment by SaeidehTD** [comment] 2022-03-31 17:12
<img width="261" alt="Screen Shot 2022-03-31 at 10 11 28 AM" src="https://user-images.githubusercontent.com/69165388/161111959-201aa775-f185-4543-8152-8a1b5a245b03.png">

**Comment by SaeidehTD** [comment] 2022-03-31 17:13
Hi, Hope you can see this. So there is an enrichment for non-eQTL variants in the significant GWAS based on this labeling however it should be the opposite.

**Comment by SaeidehTD** [comment] 2022-03-31 17:25
I also have another question and appreciate if you can help with that. Is there any way to see all the eQTL positive SNP in a region based on just the tissue? For example, in your example, You indicate eQTL data for BBS1 in whole blood, what if we want to see all eQTL data for that region of interest for whole blood and independent of the gene of interest.

**Comment by TGDrivas** [comment] 2022-03-31 18:02
Hmm you're right, this does look like a labeling issue. Would you be able to share with me the data you're working with so I can try to figure out where things are going wrong? You can email them to me at theodore.drivas@pennmedicine.upenn.edu

Regarding your second question, I think maybe the argument GeneList would be helpful to you. If you look at example 1 in the documentation, you can see how you can supply eQTpLot with a list of genes in the region of interest, and the package will output  a crude estimation of which gene's eQTL data most closely correlates with the GWAS signal observed at this locus.

For example, you could use a command like the following, replacing GENE1, etc. with your genes of interest:

eQTpLot(GWAS.df = your.GWAS.df, eQTL.df = your.eQTL.df, gene = c("GENE1", "GENE2", "GENE3"), 
          gbuild = "hg19",  trait = "LDL", tissue =  "Whole_Blood", GeneList = T)

**Comment by SaeidehTD** [comment] 2022-03-31 18:12
Thanks. I will email the input files.

**Comment by TGDrivas** [comment] 2022-04-01 17:07
Hi Saeideh, I believe the problem is fixed now! There was an error in the labelling of the enrichment plot, as you pointed out. Please let me know if the update has fixed your problem :)

**Comment by SaeidehTD** [comment] 2022-04-01 17:56
Hi Teddy,

Yes, it is fixed. Thanks :). I have another question that thought you might
be able to help me with. So, I have been trying to generate the p-p plot in
R using the same data sets I have used for your package. While my scatter
plot exactly looks like yours (the points completely match), my linear
regression p-value and r2 are different than when I use your package. Did
you guys use log10 for calculating the p-value and r2 or just the values?
Any thought on why this could happen is appreciated.

Thanks,

Saeideh

**Comment by TGDrivas** [comment] 2022-04-01 18:22
Glad the plot looks good now! For the Pearson correlation and linear regression, they were calculated as follows (note that only SNPs that are present in both the GWAS and eQTL data are used for the following calculations):

cor.test(-log10(Peqtl), -log10(Pgwas), method = "pearson")

geom_smooth(data=data, aes(y=-log10(Pgwas),  x=-log10(Peqtl)), color = "black", method = "lm", formula = (y ~ x))

**Closed** 2022-04-19 18:17 UTC
